import type { Email, AgentActivity, CustomFolder, FinancialDocument, CalendarEvent, CalendarParticipant, QuarantineAction, EmailThread, TimezoneConflict } from "@shared/schema";

const now = new Date();
const h = (hoursAgo: number) => new Date(now.getTime() - hoursAgo * 60 * 60 * 1000);

export const DEMO_EMAILS: Email[] = ([
  {
    id: "demo-1",
    userId: "demo",
    from: "Sarah Chen",
    fromEmail: "sarah.chen@stripe.com",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "",
    bcc: "",
    subject: "Invoice #INV-2024-0892 — Payment Due March 15",
    body: "<p>Hi there,</p><p>Your monthly invoice for EOMail Pro services is ready. The total amount due is <strong>$149.00</strong> for the billing period of Feb 1 - Feb 28, 2026.</p><p>Payment is due by March 15, 2026. You can view and pay your invoice at the link below.</p><p>If you have any questions about this invoice, please don't hesitate to reach out.</p><p>Best regards,<br/>Sarah Chen<br/>Billing Team, Stripe</p>",
    preview: "Your monthly invoice for EOMail Pro services is ready. The total amount due is $149.00...",
    timestamp: h(2),
    read: false,
    starred: true,
    folder: "inbox",
    labels: ["finance"],
    attachments: 1,
    aiSummary: "Monthly invoice from Stripe for $149.00 due March 15. Routine billing for EOMail Pro subscription.",
    aiCategory: "finance",
    aiUrgency: "medium",
    aiSuggestedAction: "review",
    aiDraftReply: null,
    aiSpamScore: 0,
    aiSpamReason: null,
    aiProcessed: true,
    createdAt: h(2),
  },
  {
    id: "demo-2",
    userId: "demo",
    from: "Marcus Johnson",
    fromEmail: "marcus.j@techventures.io",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "team@techventures.io",
    bcc: "",
    subject: "Re: Q1 Strategy Meeting — Confirmed for Thursday 2pm",
    body: "<p>Hey,</p><p>Just confirming our Q1 strategy meeting for <strong>Thursday at 2:00 PM PST</strong>. We'll be covering:</p><ul><li>Revenue projections for Q1</li><li>Product roadmap updates</li><li>Hiring plan review</li><li>Partnership pipeline</li></ul><p>I've sent a calendar invite. Conference room B or Zoom link in the invite.</p><p>Looking forward to it!<br/>Marcus</p>",
    preview: "Just confirming our Q1 strategy meeting for Thursday at 2:00 PM PST. We'll be covering revenue projections...",
    timestamp: h(4),
    read: false,
    starred: false,
    folder: "inbox",
    labels: ["work"],
    attachments: 0,
    aiSummary: "Q1 strategy meeting confirmed for Thursday 2pm PST. Agenda: revenue, roadmap, hiring, partnerships.",
    aiCategory: "scheduling",
    aiUrgency: "high",
    aiSuggestedAction: "reply",
    aiDraftReply: "Hi Marcus,\n\nThanks for confirming. I'll be there at 2 PM. I'd like to add a brief discussion about our AI integration timeline if there's room on the agenda.\n\nSee you Thursday!",
    aiSpamScore: 0,
    aiSpamReason: null,
    aiProcessed: true,
    threadId: "thread-q1-strategy",
    threadSubject: "Q1 Strategy Meeting",
    threadPosition: 1,
    createdAt: h(4),
  },
  {
    id: "demo-3",
    userId: "demo",
    from: "Security Team",
    fromEmail: "security@google.com",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "",
    bcc: "",
    subject: "Security Alert: New sign-in from Chrome on MacBook Pro",
    body: "<p>We noticed a new sign-in to your Google Account on a <strong>MacBook Pro</strong> using <strong>Chrome</strong>.</p><p><strong>Details:</strong></p><ul><li>Time: March 7, 2026, 9:45 AM PST</li><li>Location: San Francisco, CA</li><li>Device: MacBook Pro</li><li>Browser: Chrome 122</li></ul><p>If this was you, you can ignore this message. If you don't recognize this activity, please secure your account immediately.</p>",
    preview: "We noticed a new sign-in to your Google Account on a MacBook Pro using Chrome...",
    timestamp: h(6),
    read: true,
    starred: false,
    folder: "inbox",
    labels: ["important"],
    attachments: 0,
    aiSummary: "Google sign-in alert from MacBook Pro in San Francisco. Appears legitimate based on your usual location.",
    aiCategory: "security",
    aiUrgency: "low",
    aiSuggestedAction: "archive",
    aiDraftReply: null,
    aiSpamScore: 0,
    aiSpamReason: null,
    aiProcessed: true,
    createdAt: h(6),
  },
  {
    id: "demo-4",
    userId: "demo",
    from: "Emily Rodriguez",
    fromEmail: "emily@designhq.co",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "",
    bcc: "",
    subject: "Brand refresh mockups ready for review",
    body: "<p>Hi!</p><p>The brand refresh mockups are ready for your review. I've attached the latest designs including:</p><ul><li>Updated logo variations (light/dark)</li><li>Color palette refinements</li><li>Typography system</li><li>Business card and letterhead templates</li></ul><p>I'm especially excited about the new gradient treatment on the logo. Let me know your thoughts!</p><p>Best,<br/>Emily</p>",
    preview: "The brand refresh mockups are ready for your review. I've attached the latest designs...",
    timestamp: h(8),
    read: false,
    starred: true,
    folder: "inbox",
    labels: ["design"],
    attachments: 4,
    aiSummary: "Brand refresh designs ready: logo, colors, typography, and templates. Designer is requesting feedback.",
    aiCategory: "design",
    aiUrgency: "medium",
    aiSuggestedAction: "reply",
    aiDraftReply: "Hi Emily,\n\nThese look fantastic! I love the gradient treatment on the logo. A few quick thoughts:\n\n1. The dark mode variation is really strong\n2. Can we explore a slightly bolder weight for the heading font?\n3. The business card layout is perfect\n\nLet's schedule a quick call to discuss the refinements. Does tomorrow afternoon work?",
    aiSpamScore: 0,
    aiSpamReason: null,
    aiProcessed: true,
    threadId: "thread-brand-refresh",
    threadSubject: "Brand refresh",
    threadPosition: 2,
    createdAt: h(8),
  },
  {
    id: "demo-5",
    userId: "demo",
    from: "AWS Billing",
    fromEmail: "no-reply@aws.amazon.com",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "",
    bcc: "",
    subject: "Your AWS bill for February 2026 is available",
    body: "<p>Hello,</p><p>Your AWS bill for <strong>February 2026</strong> is now available.</p><p><strong>Total: $2,347.82</strong></p><p>This represents a 12% increase from last month, primarily due to increased EC2 and RDS usage.</p><p>View your complete bill and usage details in the AWS Billing Console.</p>",
    preview: "Your AWS bill for February 2026 is now available. Total: $2,347.82. This represents a 12% increase...",
    timestamp: h(12),
    read: true,
    starred: false,
    folder: "inbox",
    labels: ["finance"],
    attachments: 0,
    aiSummary: "AWS bill for Feb 2026: $2,347.82 (+12% from Jan). Increase driven by EC2 and RDS usage. May want to review resource utilization.",
    aiCategory: "finance",
    aiUrgency: "medium",
    aiSuggestedAction: "review",
    aiDraftReply: null,
    aiSpamScore: 0,
    aiSpamReason: null,
    aiProcessed: true,
    createdAt: h(12),
  },
  {
    id: "demo-6",
    userId: "demo",
    from: "Alex Kim",
    fromEmail: "alex.kim@acmecorp.com",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "",
    bcc: "",
    subject: "Urgent: Client presentation moved to tomorrow 9am",
    body: "<p>Hey,</p><p>Heads up \u2014 the Acme Corp client presentation has been <strong>moved up to tomorrow at 9:00 AM</strong> (was originally Friday).</p><p>The client's CEO is flying out Thursday evening so we need to present earlier. Can you have the final deck ready by tonight?</p><p>Key slides we still need:</p><ol><li>ROI analysis (slide 12)</li><li>Implementation timeline (slide 15)</li><li>Competitive comparison (slide 18)</li></ol><p>I know it's tight but this is a $500K deal. Let me know if you need anything from my end.</p><p>Thanks,<br/>Alex</p>",
    preview: "Heads up -- the Acme Corp client presentation has been moved up to tomorrow at 9:00 AM...",
    timestamp: h(1),
    read: false,
    starred: false,
    folder: "inbox",
    labels: ["work", "important"],
    attachments: 0,
    aiSummary: "URGENT: Client presentation moved to tomorrow 9am (was Friday). Need final deck tonight. $500K deal at stake.",
    aiCategory: "action-required",
    aiUrgency: "high",
    aiSuggestedAction: "reply",
    aiDraftReply: "Hi Alex,\n\nGot it \u2014 I'll prioritize this. I can have the ROI analysis and implementation timeline done by 7 PM tonight. I'll need your input on the competitive comparison slide though.\n\nCan you send me the latest competitor pricing data in the next hour?\n\nWe've got this.",
    aiSpamScore: 0,
    aiSpamReason: null,
    aiProcessed: true,
    createdAt: h(1),
  },
  {
    id: "demo-7",
    userId: "demo",
    from: "TechCrunch Daily",
    fromEmail: "newsletter@techcrunch.com",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "",
    bcc: "",
    subject: "AI Startup Funding Hits Record $42B in Q1 2026",
    body: "<p><strong>Today's Top Stories</strong></p><p><strong>1. AI Startup Funding Hits Record $42B</strong><br/>Venture capital investments in AI startups reached an all-time high of $42 billion in Q1 2026, driven by enterprise adoption of agentic AI systems.</p><p><strong>2. Apple Launches AI-First MacBook</strong><br/>Apple unveiled a new MacBook line with dedicated Neural Engine chips, promising 5x faster on-device AI inference.</p><p><strong>3. EU AI Act Enforcement Begins</strong><br/>The European Union has started enforcing its AI Act, with the first compliance audits targeting high-risk AI systems in healthcare and finance.</p>",
    preview: "AI Startup Funding Hits Record $42B in Q1 2026. Today's Top Stories...",
    timestamp: h(14),
    read: true,
    starred: false,
    folder: "inbox",
    labels: [],
    attachments: 0,
    aiSummary: "Tech newsletter: AI funding record $42B, Apple AI MacBook launch, EU AI Act enforcement begins.",
    aiCategory: "newsletter",
    aiUrgency: "low",
    aiSuggestedAction: "archive",
    aiDraftReply: null,
    aiSpamScore: 5,
    aiSpamReason: null,
    aiProcessed: true,
    createdAt: h(14),
  },
  {
    id: "demo-8",
    userId: "demo",
    from: "Lisa Park",
    fromEmail: "lisa.park@investor.vc",
    to: "Demo User",
    toEmail: "demo@eomail.co",
    cc: "",
    bcc: "",
    subject: "Follow-up: Series A term sheet discussion",
    body: "<p>Hi,</p><p>Great meeting yesterday. Our team was impressed with the traction and the AI-first approach.</p><p>We'd like to move forward with the term sheet discussion. Here's what we're thinking:</p><ul><li>Investment: $8M Series A</li><li>Pre-money valuation: $32M</li><li>Board seat: 1 investor seat</li><li>Pro-rata rights for follow-on</li></ul><p>Can we set up a call with your counsel this week? We'd like to have terms finalized by end of month.</p><p>Looking forward to partnering with you.</p><p>Best,<br/>Lisa Park<br/>Managing Partner, Horizon Ventures</p>",
    preview: "Great meeting yesterday. We'd like to move forward with the term sheet discussion...",
    timestamp: h(3),
    read: false,
    starred: true,
    folder: "inbox",
    labels: ["finance", "important"],
    attachments: 0,
    aiSummary: "Series A term sheet: $8M at $32M pre-money from Horizon Ventures. They want to finalize by end of month. HIGH PRIORITY.",
    aiCategory: "finance",
    aiUrgency: "high",
    aiSuggestedAction: "reply",
    aiDraftReply: "Hi Lisa,\n\nThank you for the follow-up and for the positive feedback from your team. We're excited about the possibility of partnering with Horizon Ventures.\n\nThe proposed terms look like a strong starting point. I'll connect you with our counsel \u2014 I'll have them reach out by Wednesday to schedule a call.\n\nLooking forward to moving this forward.",
    aiSpamScore: 0,
    aiSpamReason: null,
    aiProcessed: true,
    createdAt: h(3),
  },
  {
    id: "demo-9",
    userId: "demo",
    from: "Demo User",
    fromEmail: "demo@eomail.co",
    to: "Alex Kim",
    toEmail: "alex.kim@acmecorp.com",
    cc: "",
    bcc: "",
    subject: "Re: Q4 Results Summary",
    body: "<p>Hi Alex,</p><p>Here's the Q4 results summary as discussed. Revenue was up 28% QoQ and we exceeded our targets on all key metrics.</p><p>Let me know if you need any additional details.</p><p>Best</p>",
    preview: "Here's the Q4 results summary as discussed. Revenue was up 28% QoQ...",
    timestamp: h(20),
    read: true,
    starred: false,
    folder: "sent",
    labels: [],
    attachments: 0,
    aiSummary: null,
    aiCategory: null,
    aiUrgency: null,
    aiSuggestedAction: null,
    aiDraftReply: null,
    aiSpamScore: null,
    aiSpamReason: null,
    aiProcessed: false,
    createdAt: h(20),
  },
  {
    id: "demo-10",
    userId: "demo",
    from: "Demo User",
    fromEmail: "demo@eomail.co",
    to: "Emily Rodriguez",
    toEmail: "emily@designhq.co",
    cc: "",
    bcc: "",
    subject: "Re: Brand refresh kickoff",
    body: "<p>Hi Emily,</p><p>Let's get started on the brand refresh. I'll send over the brand guidelines and inspiration board by EOD.</p><p>Thanks!</p>",
    preview: "Let's get started on the brand refresh. I'll send over the brand guidelines...",
    timestamp: h(48),
    read: true,
    starred: false,
    folder: "sent",
    labels: [],
    attachments: 0,
    aiSummary: null,
    aiCategory: null,
    aiUrgency: null,
    aiSuggestedAction: null,
    aiDraftReply: null,
    aiSpamScore: null,
    aiSpamReason: null,
    aiProcessed: false,
    threadId: "thread-brand-refresh",
    threadSubject: "Brand refresh",
    threadPosition: 1,
    createdAt: h(48),
  },
] as unknown as Email[]);

export const DEMO_COUNTS: Record<string, number> = {
  inbox: 8,
  starred: 3,
  sent: 2,
  drafts: 0,
  "pending-approvals": 3,
  archive: 0,
  spam: 0,
  trash: 0,
  all: 10,
  finops: 2,
  calendar: 1,
  security: 2,
};

export const DEMO_AGENT_ACTIVITY: AgentActivity[] = [
  {
    id: "demo-agent-1",
    userId: "demo",
    agentName: "FinOps Auto-Resolver",
    action: "Analyzed invoice #INV-2024-0892 from Stripe",
    status: "complete",
    emailId: "demo-1",
    detail: "Flagged as routine billing. No anomalies detected.",
    createdAt: h(2),
  },
  {
    id: "demo-agent-2",
    userId: "demo",
    agentName: "Chrono-Logistics Coordinator",
    action: "Scheduled Q1 strategy meeting for Thursday 2pm",
    status: "complete",
    emailId: "demo-2",
    detail: "Calendar invite detected. Meeting added to schedule.",
    createdAt: h(4),
  },
  {
    id: "demo-agent-3",
    userId: "demo",
    agentName: "Aegis Gatekeeper",
    action: "Verified Google security alert authenticity",
    status: "complete",
    emailId: "demo-3",
    detail: "DKIM/SPF passed. Legitimate alert from Google.",
    createdAt: h(6),
  },
  {
    id: "demo-agent-4",
    userId: "demo",
    agentName: "FinOps Auto-Resolver",
    action: "Flagged AWS bill increase (+12%)",
    status: "complete",
    emailId: "demo-5",
    detail: "Monthly cost up $252. Recommend reviewing EC2 instance sizes.",
    createdAt: h(12),
  },
  {
    id: "demo-agent-5",
    userId: "demo",
    agentName: "Aegis Gatekeeper",
    action: "Scanning new investor email for phishing indicators",
    status: "pending",
    emailId: "demo-8",
    detail: null,
    createdAt: h(0.5),
  },
  {
    id: "demo-agent-6",
    userId: "demo",
    agentName: "EOMail Assistant",
    action: "Generated 3 draft replies for urgent emails",
    status: "complete",
    emailId: null,
    detail: "Draft replies generated for emails from Marcus, Emily, and Alex.",
    createdAt: h(1),
  },
];

export const DEMO_CUSTOM_FOLDERS: CustomFolder[] = [
  {
    id: "demo-folder-1",
    userId: "demo",
    name: "Finance",
    parentId: null,
    icon: "folder",
    color: "emerald",
    createdAt: h(100),
  },
  {
    id: "demo-folder-2",
    userId: "demo",
    name: "Scheduling",
    parentId: null,
    icon: "folder",
    color: "blue",
    createdAt: h(100),
  },
  {
    id: "demo-folder-3",
    userId: "demo",
    name: "Newsletters",
    parentId: null,
    icon: "folder",
    color: "purple",
    createdAt: h(100),
  },
  {
    id: "demo-folder-4",
    userId: "demo",
    name: "Action Required",
    parentId: null,
    icon: "folder",
    color: "rose",
    createdAt: h(100),
  },
];

export const DEMO_BRIEFING = {
  briefing: `You have 5 unread emails requiring attention. Here's your priority breakdown:

**Urgent (2):** Alex Kim's client presentation has been moved to tomorrow 9am — you'll need the final deck tonight. Lisa Park from Horizon Ventures wants to discuss Series A terms ($8M at $32M pre-money).

**Action Required (1):** Emily Rodriguez's brand refresh mockups are ready for your review with 4 attachments.

**Financial (2):** Stripe invoice of $149 due March 15 and AWS bill of $2,347.82 (up 12% from last month — consider reviewing EC2 resource utilization).

**Informational (1):** Google security alert for a MacBook Pro sign-in from San Francisco — appears to be your device.

**Recommendation:** Start with Alex's presentation request (time-sensitive), then review Lisa's term sheet (high-value), and schedule time for Emily's design review.`,
  agentStats: [
    { name: "FinOps Auto-Resolver", completed: 2, pending: 0 },
    { name: "Chrono-Logistics Coordinator", completed: 1, pending: 0 },
    { name: "Aegis Gatekeeper", completed: 1, pending: 1 },
    { name: "EOMail Assistant", completed: 1, pending: 0 },
  ],
};

export const DEMO_USER = {
  displayName: "Demo User",
  email: "demo@eomail.co",
  avatarInitials: "DU",
  mailboxAddress: "demo@eomail.co",
  username: "demo",
};

export const DEMO_FINANCIAL_DOCUMENTS: FinancialDocument[] = ([
  {
    id: "demo-fin-1",
    userId: "demo",
    emailId: "demo-1",
    documentType: "invoice",
    status: "extracted",
    vendorName: "Stripe",
    vendorEmail: "sarah.chen@stripe.com",
    invoiceNumber: "INV-2024-0892",
    invoiceDate: h(2),
    dueDate: new Date(now.getFullYear(), now.getMonth(), 15),
    currency: "USD",
    subtotal: "149.00",
    tax: "0.00",
    shipping: null,
    discount: null,
    total: "149.00",
    lineItems: [{ description: "EOMail Pro Monthly Subscription", quantity: 1, amount: 149.0 }],
    paymentStatus: "pending",
    confidenceScore: 95,
    rawExtraction: null,
    confirmedAt: null,
    createdAt: h(2),
  },
  {
    id: "demo-fin-2",
    userId: "demo",
    emailId: "demo-5",
    documentType: "invoice",
    status: "extracted",
    vendorName: "Amazon Web Services",
    vendorEmail: "no-reply@aws.amazon.com",
    invoiceNumber: "AWS-2026-02",
    invoiceDate: h(12),
    dueDate: new Date(now.getFullYear(), now.getMonth(), 28),
    currency: "USD",
    subtotal: "2095.38",
    tax: "252.44",
    shipping: null,
    discount: null,
    total: "2347.82",
    lineItems: [
      { description: "EC2 Instances (m5.xlarge x3)", quantity: 3, amount: 1245.60 },
      { description: "RDS PostgreSQL (db.r5.large)", quantity: 1, amount: 549.78 },
      { description: "S3 Storage + Transfer", quantity: 1, amount: 300.00 },
    ],
    paymentStatus: "pending",
    confidenceScore: 91,
    rawExtraction: null,
    confirmedAt: null,
    createdAt: h(12),
  },
] as unknown as FinancialDocument[]);

export const DEMO_CALENDAR_EVENTS: (CalendarEvent & { participants?: CalendarParticipant[] })[] = ([
  {
    id: "demo-cal-1",
    userId: "demo",
    emailId: "demo-2",
    title: "Q1 Strategy Meeting",
    description: "Revenue projections, product roadmap, hiring plan, partnership pipeline",
    startTime: (() => { const d = new Date(); d.setDate(d.getDate() + ((4 - d.getDay() + 7) % 7 || 7)); d.setHours(14, 0, 0, 0); return d; })(),
    endTime: (() => { const d = new Date(); d.setDate(d.getDate() + ((4 - d.getDay() + 7) % 7 || 7)); d.setHours(15, 30, 0, 0); return d; })(),
    timezone: "America/Los_Angeles",
    location: "Conference Room B",
    meetingUrl: "https://zoom.us/j/1234567890",
    status: "pending",
    organizerEmail: "marcus.j@techventures.io",
    recurrenceRule: null,
    createdAt: h(4),
    updatedAt: h(4),
    participants: [
      { id: "demo-part-1", eventId: "demo-cal-1", email: "marcus.j@techventures.io", name: "Marcus Johnson", status: "accepted", isOptional: false, createdAt: h(4) },
      { id: "demo-part-2", eventId: "demo-cal-1", email: "demo@eomail.co", name: "Demo User", status: "pending", isOptional: false, createdAt: h(4) },
      { id: "demo-part-3", eventId: "demo-cal-1", email: "team@techventures.io", name: "Tech Ventures Team", status: "pending", isOptional: true, createdAt: h(4) },
    ],
  },
  {
    id: "demo-cal-2",
    userId: "demo",
    emailId: "demo-6",
    title: "Acme Corp Client Presentation",
    description: "Final presentation for $500K deal — ROI analysis, implementation timeline, competitive comparison",
    startTime: (() => { const d = new Date(); d.setDate(d.getDate() + 1); d.setHours(9, 0, 0, 0); return d; })(),
    endTime: (() => { const d = new Date(); d.setDate(d.getDate() + 1); d.setHours(10, 30, 0, 0); return d; })(),
    timezone: "America/New_York",
    location: null,
    meetingUrl: "https://meet.google.com/abc-defg-hij",
    status: "confirmed",
    organizerEmail: "alex.kim@acmecorp.com",
    recurrenceRule: null,
    createdAt: h(1),
    updatedAt: h(1),
    participants: [
      { id: "demo-part-4", eventId: "demo-cal-2", email: "alex.kim@acmecorp.com", name: "Alex Kim", status: "accepted", isOptional: false, createdAt: h(1) },
      { id: "demo-part-5", eventId: "demo-cal-2", email: "demo@eomail.co", name: "Demo User", status: "accepted", isOptional: false, createdAt: h(1) },
    ],
  },
] as unknown as (CalendarEvent & { participants?: CalendarParticipant[] })[]);

export const DEMO_QUARANTINE_ACTIONS: QuarantineAction[] = ([
  {
    id: "demo-quarantine-1",
    userId: "demo",
    emailId: "demo-quarantine-email-1",
    threatScore: 92,
    threatType: "phishing",
    quarantineReason: "Impersonation attempt detected: Sender claims to be PayPal but email originates from paypa1-secure.xyz domain. Contains credential harvesting link.",
    detectedUrls: ["https://paypa1-secure.xyz/login/verify", "https://paypa1-secure.xyz/account/confirm"],
    neutralizedUrls: ["https://paypa1-secure.xyz/login/verify [BLOCKED]", "https://paypa1-secure.xyz/account/confirm [BLOCKED]"],
    domainAnalysis: { registeredDaysAgo: 3, tlsValid: false, spfPass: false, dkimPass: false },
    autoQuarantined: true,
    releaseStatus: "quarantined",
    reviewedAt: null,
    createdAt: h(5),
  },
  {
    id: "demo-quarantine-2",
    userId: "demo",
    emailId: "demo-quarantine-email-2",
    threatScore: 67,
    threatType: "urgency_scam",
    quarantineReason: "High-pressure urgency language detected. Claims immediate action required to avoid account suspension. Suspicious sender domain.",
    detectedUrls: ["https://secure-verify-now.com/action"],
    neutralizedUrls: ["https://secure-verify-now.com/action [BLOCKED]"],
    domainAnalysis: { registeredDaysAgo: 14, tlsValid: true, spfPass: false, dkimPass: true },
    autoQuarantined: true,
    releaseStatus: "quarantined",
    reviewedAt: null,
    createdAt: h(18),
  },
  {
    id: "demo-quarantine-3",
    userId: "demo",
    emailId: "demo-quarantine-email-3",
    threatScore: 45,
    threatType: "suspicious_links",
    quarantineReason: "URL shortener detected in otherwise legitimate-looking email. Released after manual review confirmed safe sender.",
    detectedUrls: ["https://bit.ly/3xY9abc"],
    neutralizedUrls: null,
    domainAnalysis: null,
    autoQuarantined: true,
    releaseStatus: "released",
    reviewedAt: h(10),
    createdAt: h(24),
  },
] as unknown as QuarantineAction[]);

export const DEMO_TIMEZONE_CONFLICTS: TimezoneConflict[] = ([
  {
    id: "demo-conflict-1",
    eventId: "demo-cal-1",
    userId: "demo",
    conflictType: "outside_working_hours",
    severity: "high",
    details: "Q1 Strategy Meeting at 2:00 PM PST falls at 11:00 PM for participant in London (GMT). Consider rescheduling to accommodate all timezones.",
    resolved: false,
    createdAt: h(4),
  },
  {
    id: "demo-conflict-2",
    eventId: "demo-cal-1",
    userId: "demo",
    conflictType: "timezone_mismatch",
    severity: "medium",
    details: "Team member in Tokyo (JST) would need to join at 7:00 AM local time. Within working hours but may conflict with morning meetings.",
    resolved: false,
    createdAt: h(4),
  },
] as unknown as TimezoneConflict[]);

export const DEMO_THREAD_SUMMARIES: EmailThread[] = ([
  {
    id: "thread-brand-refresh",
    userId: "demo",
    subject: "Brand refresh",
    participants: ["Demo User", "Emily Rodriguez"],
    messageCount: 2,
    firstMessageDate: h(48),
    lastMessageDate: h(8),
    digest: "Discussion about brand refresh project. Kickoff initiated by Demo User, followed by Emily sharing completed mockups with updated logo, colors, typography, and templates for review.",
    keyPoints: [
      "Brand refresh project kicked off",
      "Mockups delivered: logo, color palette, typography, templates",
      "Designer requests feedback on gradient logo treatment",
    ],
    aiProcessed: true,
    createdAt: h(48),
    updatedAt: h(8),
  },
] as unknown as EmailThread[]);

export function getDemoEmails(folder: string): Email[] {
  if (folder === "all") return DEMO_EMAILS;
  if (folder === "starred") return DEMO_EMAILS.filter((e) => e.starred);
  return DEMO_EMAILS.filter((e) => e.folder === folder);
}
